"use client";

import { motion } from "framer-motion";
import type { ValidationReport } from "@/lib/types";
import { fmtDate } from "@/lib/utils";
import { Card, Badge, Button } from "@/components/ui/primitives";
import { ConfidenceBadge } from "@/components/ui/provenance";
import { VerdictGauge } from "@/components/report/verdict-gauge";
import { MarketSizingCard } from "@/components/report/market-sizing";
import { CompetitorTable } from "@/components/report/competitors";
import { SwotMatrix } from "@/components/report/swot";
import { GtmPlan } from "@/components/report/gtm";
import {
  DemandSignals,
  Segments,
  BusinessModels,
  RisksOpportunities,
} from "@/components/report/sections";
import { Printer, FlaskConical } from "lucide-react";

const fade = (i = 0) => ({
  initial: { opacity: 0, y: 12 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.4, delay: 0.05 * i },
});

export function ReportView({ report }: { report: ValidationReport }) {
  return (
    <div className="mx-auto max-w-6xl px-5 py-8">
      {/* Mock banner — honest about provenance. */}
      {report.mock && (
        <div className="border-signal/30 bg-signal/10 mb-5 flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm">
          <FlaskConical className="text-signal-dim h-4 w-4" />
          <span>
            <strong className="font-600">Mock report.</strong>{" "}
            <span className="text-dim">
              Generated by the built-in engine. Add API keys to switch to live
              LLM + web data — figures stay labeled either way.
            </span>
          </span>
        </div>
      )}

      {/* Verdict header: the most important answer, first. */}
      <motion.div {...fade(0)}>
        <Card className="overflow-hidden">
          <div className="grid gap-6 p-6 md:grid-cols-[auto_1fr] md:items-center">
            <div className="flex justify-center">
              <VerdictGauge score={report.score} verdict={report.verdict} />
            </div>
            <div>
              <div className="mb-2 flex flex-wrap items-center gap-2">
                <Badge tone="muted">{report.intake.stage}</Badge>
                <Badge tone="muted">{report.intake.industry}</Badge>
                <Badge tone="muted">{report.intake.region}</Badge>
                <ConfidenceBadge level={report.confidence} />
              </div>
              <h1 className="font-display text-xl font-600 leading-snug">
                {report.intake.idea}
              </h1>
              <p className="text-dim mt-2 text-sm leading-relaxed">
                {report.summary}
              </p>
              <div className="mt-4 flex items-center gap-2">
                <Button variant="outline" onClick={() => window.print()}>
                  <Printer className="h-4 w-4" />
                  Export / print
                </Button>
                {report.createdAt && (
                  <span className="text-dim font-mono text-xs">
                    {fmtDate(report.createdAt)}
                  </span>
                )}
              </div>
            </div>
          </div>
        </Card>
      </motion.div>

      {/* Risks + opportunities */}
      <motion.div {...fade(1)} className="mt-4">
        <RisksOpportunities
          risks={report.risks}
          opportunities={report.opportunities}
        />
      </motion.div>

      {/* Market */}
      <motion.div {...fade(2)} className="mt-4">
        <MarketSizingCard sizing={report.sizing} />
      </motion.div>

      <div className="mt-4 grid gap-4 md:grid-cols-2">
        <motion.div {...fade(3)}>
          <Segments segments={report.segments} />
        </motion.div>
        <motion.div {...fade(3)}>
          <DemandSignals demand={report.demand} />
        </motion.div>
      </div>

      {/* Competitors */}
      <motion.div {...fade(4)} className="mt-4">
        <CompetitorTable
          competitors={report.competitors}
          differentiators={report.differentiators}
        />
      </motion.div>

      {/* SWOT + business model */}
      <div className="mt-4 grid gap-4 md:grid-cols-2">
        <motion.div {...fade(5)}>
          <SwotMatrix swot={report.swot} />
        </motion.div>
        <motion.div {...fade(5)}>
          <BusinessModels models={report.businessModels} />
        </motion.div>
      </div>

      {/* GTM */}
      <motion.div {...fade(6)} className="mt-4">
        <GtmPlan gtm={report.gtm} />
      </motion.div>
    </div>
  );
}
